app_name = "rarian"
data_path = "%appdata%/Rarian/rarian/data"
watcher_paths = ["home/workspace"]
ignore_apps = []
ignore_paths = []
comment_identifier = "@#$"

[sleep_duration]
secs = 0
nanos = 16000
